[workspace]
members = [
    "ronin-cli",
    "ronin-init",
]

[workspace.dependencies]
nix = { version = "0.29", features = ["mount", "fs", "process"] }
anyhow = "1.0"
thiserror = "1.0"
log = "0.4"
env_logger = "0.10"
cgroups-rs = "0.5"
